# Generated by Django 3.1.2 on 2020-10-12 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.CharField(default='', max_length=255, unique=True)),
                ('login', models.CharField(default='', max_length=255, unique=True)),
                ('name', models.CharField(default='', max_length=255)),
                ('salary', models.DecimalField(decimal_places=3, default='', max_digits=10)),
            ],
            options={
                'db_table': 'employees',
            },
        ),
    ]
